# Generated by Django 2.1.5 on 2019-01-23 12:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('title', models.CharField(max_length=1024)),
                ('type', models.CharField(choices=[('paper', 'Paper'), ('data', 'Data')], max_length=10)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('slug', models.SlugField()),
                ('description', models.TextField()),
                ('url', models.URLField()),
                ('approved', models.BooleanField(default=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
    ]
